-- Schema for minimal B2B ordering system

DROP TABLE IF EXISTS IdempotencyKey;
DROP TABLE IF EXISTS OrderItem;
DROP TABLE IF EXISTS `Order`;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Customer;

CREATE TABLE Customer (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(50) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Product (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  priceCents INT NOT NULL,
  stock INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `Order` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customerId INT NOT NULL,
  status ENUM('CREATED','CONFIRMED','CANCELED') NOT NULL DEFAULT 'CREATED',
  totalCents INT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_customer FOREIGN KEY (customerId) REFERENCES Customer(id)
);

CREATE TABLE OrderItem (
  id INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT NOT NULL,
  productId INT NOT NULL,
  qty INT NOT NULL,
  unitPriceCents INT NOT NULL,
  subtotalCents INT NOT NULL,
  CONSTRAINT fk_item_order FOREIGN KEY (orderId) REFERENCES `Order`(id) ON DELETE CASCADE,
  CONSTRAINT fk_item_product FOREIGN KEY (productId) REFERENCES Product(id)
);

CREATE TABLE IdempotencyKey (
  `key` VARCHAR(255) PRIMARY KEY,
  targetType VARCHAR(50) NOT NULL,
  targetId INT NOT NULL,
  status VARCHAR(20) NOT NULL,
  responseBody JSON,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expiresAt TIMESTAMP NULL
);


